matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_install:
        - nvm install 6
        - node --version
      install:
        - npm install
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      script:
        - cd android && ./gradlew assembleRelease
    - language: objective-c
      os: osx
      osx_image: xcode8.2
      before_install:
        - nvm install 8
        - npm install -g yarn
        - yarn --version
        - npm install -g react-native-cli
      install:
        - yarn install
      xcode_project: ios/myshine.xcodeproj
      script:
        - react-native run-ios
